server:
  port: 8081
  
  servlet:
    context-path: /product-mgmt
  
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_mgmt
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

 #this is for swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
          
  application:
    name: PRODUCT-MGMT
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostName: localhost    

  